server:
  port: 8081

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    # Supabase connection
    url: jdbc:postgresql://${DB_HOST:aws-0-ap-southeast-1.pooler.supabase.com}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres.xauxrvolraonrrxavkrt}
    password: ${DB_PASSWORD:postgres@1234}
    driver-class-name: org.postgresql.Driver

  flyway:
    # Ensures Flyway runs migrations on application startup
    enabled: true
    # Tells Flyway where your migration SQL files live
    locations: classpath:db/migration

  thymeleaf:
    check-template-location: false

mybatis:
  # Points to the XML mapper directory we just set up
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: coffee.api.config
  # Allows using short aliases (like resultType="User") in your XML files
  configuration:
    # Converts snake_case columns (e.g., first_name) to camelCase fields (e.g., firstName)
    map-underscore-to-camel-case: true
    jdbc-type-for-null: OTHER
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  cors:
    allowed-origins:
      - "http://localhost:5173"
      - "http://localhost:3000"
    allowed-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "PATCH"
      - "OPTIONS"
    allowed-headers:
      - "*"
    allow-credentials: true

storage:
  supabase:
    enabled: true
    bucket-name: ${SUPABASE_BUCKET_NAME:drinks}
    region: ${SUPABASE_REGION:ap-southeast-1}
    endpoint: ${SUPABASE_ENDPOINT:https://xauxrvolraonrrxavkrt.storage.supabase.co/storage/v1/s3}
    public-url: ${SUPABASE_PUBLIC_URL:https://xauxrvolraonrrxavkrt.supabase.co/storage/v1/object/public}
    access-key: ${SUPABASE_ACCESS_KEY:0c03e80fa11360e1d89d67accc97e881}
    secret-key: ${SUPABASE_SECRET_KEY:22991f32da268f8012e5fe40185b7eccba4506d41638bc6f474a4bc47fe47c8c}

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.orm.results: trace # Logs the actual data binding values