spring:
  config:
    activate:
      on-profile: prod

  datasource:
    # Changed 'localhost' to ${DB_HOST:localhost} so it adapts to the Docker network container name
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:coffee-shop-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres@1234}
    driver-class-name: org.postgresql.Driver

  flyway:
    # Ensures Flyway runs migrations on application startup
    enabled: true
    # Tells Flyway where your migration SQL files live
    locations: classpath:db/migration

mybatis:
  # Points to the XML mapper directory we just set up
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: coffee.api.config
  # Allows using short aliases (like resultType="User") in your XML files
  configuration:
    # Converts snake_case columns (e.g., first_name) to camelCase fields (e.g., firstName)
    map-underscore-to-camel-case: true
    jdbc-type-for-null: OTHER
    # Directs MyBatis to route its internal statements into your slf4j/logback stream
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: info
    # Keep SQL execution hidden unless diagnosing an emergency
    org.hibernate.SQL: error
    org.hibernate.orm.results: error