services:
  postgres-db:
    image: postgres:16-alpine
    container_name: coffee-shop-db-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@1234
      POSTGRES_DB: coffee-shop-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d coffee-shop-db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: